WIP: feat(discovery): Add a remote_relabel component
grafana/alloy pull request #1368
Opened 2024-07-26 16:04 UTC by simonswine

This allows to receive discovery relabeling rules from a remote server
using a websocket connection.

```tasklist
- [ ] Ensure keepalive behaviour is configurable
- [ ] Finish target sending tests
```

2024-08-22 16:13 UTC, korniltsev commented on internal/component/discovery/remote_relabel/remote_relabel.go
> +	// TODO: This should come from Alloy
should this be addressed before merging PR?

2024-08-22 17:20 UTC, korniltsev approved these changes
The code looks good to me, nice and simple.

Remember  to update changelog, docs and API depdendency once it is tagged

2024-08-26 20:20 UTC, clayton-cornell approved these changes
A couple of minor non-blocking doc suggestions

2024-08-26 20:20 UTC, clayton-cornell commented on docs/sources/reference/components/discovery/discovery.remote_relabel.md
> +| `targets` | `list(map(string))` | Targets to relabel |         | yes      |
```suggestion
| `targets` | `list(map(string))` | Targets to relabel. |         | yes      |
```

2024-08-26 20:20 UTC, clayton-cornell commented on docs/sources/reference/components/discovery/discovery.remote_relabel.md
> +| `url`                 | `string`   | Full URL to the websocket server. Needs to start with ws:// wss:// |           | yes      |
```suggestion
| `url`                 | `string`   | Full URL to the websocket server. Must start with `ws://` or `wss://`. |           | yes      |
```

2024-08-28 11:01 UTC, wildum commented
Hey, thanks for opening a PR, that's an interesting idea :) Adding such a component is a big deal, it would have been better to discuss it over a [proposal](https://github.com/grafana/alloy/blob/main/docs/design/README.md) (it's not too late to create one now and use this PR as a POC).
I would like to know a bit more about the problem it is trying to solve and whether [modules](https://grafana.com/docs/alloy/latest/get-started/modules/) or [remotecfg](https://grafana.com/docs/alloy/latest/reference/config-blocks/remotecfg/) could be a solution.

2024-08-28 11:03 UTC, wildum requested changes
^ blocking the PR for now till above's comment is clarified

2025-01-31 13:09 UTC, simonswine commented
We will implement this slightly different

2025-01-31 13:09 UTC, closed without merging