fix(helm): explicitly include namespace in manifests
grafana/alloy pull request #1606
Opened 2024-09-04 08:24 UTC by valorl

Currently, most of the manifests omit `.metadata.namespace`.

This works fine with `helm install` / `helm upgrade` where all the manifests without a namespace will be installed to `--namespace` anyway.

However, `helm template` will produce the manifests as-is (with no namespace), regardless of `--namespace`, forcing users to add the namespace manually or use more tooling.

This change adds the namespace to all manifests.

#### PR Description

#### Which issue(s) this PR fixes

#### Notes to the Reviewer

#### PR Checklist

- [ ] CHANGELOG.md updated
- [ ] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

2024-09-04 08:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/alloy?pullRequest=1606) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/alloy?pullRequest=1606) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/alloy?pullRequest=1606) it.</sub>

2024-11-08 06:22 UTC, neopointer commented on operations/helm/charts/alloy/templates/cluster_service.yaml
> +  namespace: {{ include "alloy.namespace" . }}
@valorl excuse my ignorance, but why use `alloy.namespace` instead of `Release.Namespace`?

2024-11-08 06:25 UTC, neopointer commented
@clayton-cornell I'm just tagging a random contributor here. What is this PR missing to get merged?

2024-11-13 20:14 UTC, clayton-cornell commented
@neopointer It looks like this one got missed in the shuffle. Lets see if we can get a developer/maintainer review happening here.

@grafana/grafana-alloy-maintainers can someone form the team take a look at this?

2024-11-18 18:10 UTC, mattdurham approved these changes
LGTM

2024-11-18 18:10 UTC, mattdurham commented
@petewall any thoughts on if this causes any issue?

2024-11-18 18:19 UTC, mattdurham commented
This PR #2044 seems to be the most active and achieves the same result?

2024-11-18 18:20 UTC, mattdurham requested changes
Looking to see if we can consolidate PRs

2024-12-05 11:40 UTC, valorl commented
Closing in favor of #2044

2024-12-05 11:40 UTC, closed without merging